language: node_js
dist: trusty
group: edge
arch: arm64-graviton2
sudo: required
install: true
if: tag IS blank
jobs:
  include:
    - stage: Build
      name: "Production"
      script:
        - npm install    || travis_terminate 1;
        - npm run lint    || travis_terminate 1;
        - npm run build   || travis_terminate 1;
      workspaces:
        create:
          name: production_build
          paths:
            - packages/*/dist
            - packages/*/build

    - stage: Build
      name: "Development"
      script:
        - npm install    || travis_terminate 1;
        - npm run lint    || travis_terminate 1;
        - npm run build:dev   || travis_terminate 1;
      workspaces:
        create:
          name: dev_build
          paths:
            - packages/*/dist
            - packages/*/build
    
    - stage: Tests
      workspaces:
        use: dev_build
      name: “Unit Tests”
      script:
        - npm run ci:test-unit || travis_terminate 1;

    - stage: Tests
      workspaces:
        use: dev_build
      name: "E2E Tests - layouts"
      script:
        - npm run ci:test-e2e-layouts || travis_terminate 1;

    - stage: Tests
      workspaces:
        use: dev_build
      name: "E2E Tests - styleParams"
      script:
        - npm run ci:test-e2e-styleParams || travis_terminate 1;
    - stage: Tests
      workspaces:
        use: dev_build
      name: "E2E Tests - integration"
      script:
        - npm run ci:test-e2e-integration || travis_terminate 1;

    - stage: Tests
      workspaces:
        use: dev_build
      name: "E2E Tests - ssr"
      script:
        - npm run ci:test-e2e-ssr || travis_terminate 1;

    - stage: Deploy
      if: NOT type IN (pull_request) AND branch = master
      workspaces:
        use: production_build
      script:
        - git remote set-url origin "https://wix:${GITHUB_TOKEN}@github.com/wix/pro-gallery.git" > /dev/null 2>&1
        - git checkout master
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
        - npm run publishNewAlpha

notifications:
  email:
    recipients:
    - guyso@wix.com
