language: node_js
os: osx
node_js:
  - "10"
# This addon ensure we run the latest stable chrome which support headless mode
addons:
  chrome: stable
cache:
  directories:
    - node_modules
install:
- npm install
script:
- npm run lint    || travis_terminate 1;
- npm run build   || travis_terminate 1;
- npm run test    || travis_terminate 1;
- npm run publish || travis_terminate 1;
- npm run deploy  || travis_terminate 1;
notifications:
  email:
    recipients:
    - guyso@wix.com

