language: node_js
dist: xenial
addons:
  chrome: stable
cache:
  directories:
    - node_modules
sudo: required
node_js:
  - "10.15.3"
# env:
#   global:
#     - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
# allow headful tests
before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  # - "export DISPLAY=:99.0"
  # - "sh -e /etc/init.d/xvfb start"
install:
- npm install
script:
- npm run lint    || travis_terminate 1;
- npm run build   || travis_terminate 1;
- npm run test    || travis_terminate 1;
- npm run publish || travis_terminate 1;
- npm run deploy  || travis_terminate 1;
notifications:
  email:
    recipients:
    - guyso@wix.com

